### ISSUE TITLE
Forge server doesn't start with ForgeAuth

### ISSUE THREAD

**Issue by hvedor** [kanavis/ForgeAuth#1]
`[12:31:20] [Server thread/FATAL] [FML]: Fatal errors were detected during the transition from SERVER_ABOUT_TO_START to SERVER_STARTING. Loading cannot continue
[12:31:20] [Server thread/FATAL] [FML]: 
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

        | State    | ID                | Version      | Source                                        | Signature                                |
        |:-------- |:----------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
        | UCHIJAAA | minecraft         | 1.12.2       | minecraft.jar                                 | None                                     |
        | UCHIJAAA | mcp               | 9.42         | minecraft.jar                                 | None                                     |
        | UCHIJAAA | FML               | 8.0.99.99    | forge-1.12.2-14.23.0.2528-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | UCHIJAAA | forge             | 14.23.0.2528 | forge-1.12.2-14.23.0.2528-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | UCHIJAAA | biomesoplenty     | 7.0.1.2399   | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar | None                                     |
        | UCHIJAAE | forgelogin        | 0.2          | forgelogin-0.2.jar                            | None                                     |
        | UCHIJAAA | ic2               | 2.8.97-ex112 | industrialcraft_2_2.8.97_ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
        | UCHIJAAA | mercurius_updater | 1.0          | MercuriusUpdater-1.12.2.jar                   | None                                     |

[12:31:20] [Server thread/FATAL] [FML]: The following problems were captured during this phase
[12:31:20] [Server thread/ERROR] [FML]: Caught exception from forgelogin (java.lang.NoSuchMethodError: net.minecraft.util.text.Style.setBold(Ljava/lang/Boolean;)Lnet/minecraft/util/text/Style;)
[12:31:20] [Server thread/ERROR] [FML]: A fatal exception occurred during the server starting event
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Forge Login (forgelogin)

Caused by: java.lang.NoSuchMethodError: net.minecraft.util.text.Style.setBold(Ljava/lang/Boolean;)Lnet/minecraft/util/text/Style;
        at pw.kanavis.forgelogin.auth.AuthCommand.<clinit>(AuthCommand.java:31) ~[AuthCommand.class:?]
        at pw.kanavis.forgelogin.ForgeLogin.serverStart(ForgeLogin.java:48) ~[ForgeLogin.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606) ~[forge-1.12.2-14.23.0.2528-universal.jar:?]
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) ~[forge-1.12.2-14.23.0.2528-universal.jar:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) ~[forge-1.12.2-14.23.0.2528-universal.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:769) [Loader.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:295) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:306) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[12:31:20] [Server thread/INFO]: Stopping server
`

**Comment by kanavis** [comment]
Please provide all output when server starts.
Otherwise, provide me your server folder to email or some way else.

**Comment by kanavis** [comment]
Fixed, removed .setBold() on messages for better backwards compatibility.
Release 0.2 rebuilt.
